<?php

namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
        });
    }

    public function render($request, Throwable $e)
    {
        if ($request->segment(1) == "api" && $e instanceof ModelNotFoundException)
        {
            return response()
                ->json([
                    'message' => "Kayıt bulunamadı"
                ])
                ->setStatusCode(404)
                ->setCharset("utf-8")
                ->header("content-type", "application/json")
                ->setEncodingOptions(JSON_UNESCAPED_UNICODE)
                ->setEncodingOptions(JSON_UNESCAPED_SLASHES);;
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub

    }
}
